
Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-gxbq7[0m
{"level":"warn","ts":1576097825.3737373,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1576097825.3741715,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-vc44m[0m
{"level":"warn","ts":1576097826.3306053,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1576097826.332101,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1229-in-7sgf5[0m
{"level":"warn","ts":1576097832.402736,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1576097836.1126769,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:7becc696a34e73f0dce730531c398fd0f0d6fda7,1229:bc42d1fc1f39867c67285909dfa65c138f08247a
DEBUG: ran git fetch --unshallow origin bc42d1fc1f39867c67285909dfa65c138f08247a: 7becc696a34e73f0dce730531c398fd0f0d6fda7: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 7becc696a34e73f0dce730531c398fd0f0d6fda7 in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge bc42d1fc1f39867c67285909dfa65c138f08247a in 
Merged SHA 7a0728bdc244552358ca6967a51d0b3aedbcdde9 with commit message 'Merge commit 'bc42d1fc1f39867c67285909dfa65c138f08247a'' into base branch master
Merged SHA bc42d1fc1f39867c67285909dfa65c138f08247a with commit message 'Add test updating between apiVersion' into base branch master
Merged SHA cb4884185c5c42e0111f180ba673e280b93daad0 with commit message 'Add test deploying different apiVersions' into base branch master
Merged SHA db46c2102e6ff8d15865ed75ed855d76b901e95e with commit message 'Register all types and webhooks' into base branch master
Merged SHA d0b40d7e4a983699cecf41ad206e9adc90886a6a with commit message 'Make apiVersion as variable' into base branch master
Merged SHA 5688fba761ac294d206848bd68ed67a6dc60c198 with commit message 'Update helm charts' into base branch master
Merged SHA 7cf3a40af11d858fbc21b05f0211aee84754f11f with commit message 'Apply changes to api/v1 and api/v1alpha3' into base branch master
Merged SHA 2cb4cb749751e9bcd60361f8cef6118098dbae19 with commit message 'Add new versions to PROJECT' into base branch master
Merged SHA 34e844d421a1c9a3eb78f4dc523ce84be3ce12fe with commit message 'Update CRD an webhook manifest' into base branch master
Merged SHA 7b4670c4536ffeb0e2029165b1866f784b6cbc54 with commit message 'Add v1alpha3 package' into base branch master
Merged SHA 126751a2a150dda53dcd728ecea507a9ff66c633 with commit message 'Set v1 as storagevesion' into base branch master
Merged SHA d4de26841b2f2e3975cb9a985757fdf9ccdb0399 with commit message 'Point imports to v1' into base branch master
Merged SHA fa84d607d706ad69b49e0bcf370620835f534841 with commit message 'Add v1 of the CRD' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1229
+ BUILD_NUMBER=23
+ PIPELINE_CONTEXT=integration
++ cat
+++ date
+ COMMENT_MSG='Wed Dec 11 20:57:21 UTC 2019
The logs for [integration] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/23.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1229 --build=23'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1229 '--comment=Wed Dec 11 20:57:21 UTC 2019
The logs for [integration] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/23.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1229 --build=23'

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1229-in-sg2d2[0m
{"level":"warn","ts":1576097844.20163,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1576097844.2059627,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /pvc/pr-build-comment/workspace\""}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1229-in-ckzbw[0m
{"level":"warn","ts":1576097844.4655461,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1576097844.798155,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"cp -r /workspace/source/. /pvc/pr-build-comment/workspace\""}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mend-to-end[0m and container [32mstep-credential-initializer-94t96[0m
{"level":"warn","ts":1576097849.1942444,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1576097849.1947098,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mend-to-end[0m and container [32mstep-working-dir-initializer-nnmft[0m
{"level":"warn","ts":1576097850.1790037,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1576097850.1805465,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mend-to-end[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mend-to-end[0m and container [32mstep-create-dir-workspace-n6xfk[0m
{"level":"warn","ts":1576097856.2878487,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1576097856.2895918,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mend-to-end[0m and container [32mstep-source-copy-workspace-kl2g7[0m
{"level":"warn","ts":1576097856.5719144,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1576097858.1675906,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"cp -r /pvc/pr-build-comment/workspace/. /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1229-in-2mvr4-23[0m stage [32mend-to-end[0m and container [32mstep-test-end-to-end[0m
Starting Docker: docker.
[SETUP] Waiting for Docker to be ready, sleeping for 1 seconds ...
kind create cluster --config kind_config.yaml
Creating cluster "kind" ...
 ‚Ä¢ Ensuring node image (kindest/node:v1.15.3) üñº  ...
 ‚úì Ensuring node image (kindest/node:v1.15.3) üñº
 ‚Ä¢ Preparing nodes üì¶üì¶  ...
 ‚úì Preparing nodes üì¶üì¶
 ‚Ä¢ Creating kubeadm config üìú  ...
 ‚úì Creating kubeadm config üìú
 ‚Ä¢ Starting control-plane üïπÔ∏è  ...
 ‚úì Starting control-plane üïπÔ∏è
 ‚Ä¢ Installing CNI üîå  ...
 ‚úì Installing CNI üîå
 ‚Ä¢ Installing StorageClass üíæ  ...
 ‚úì Installing StorageClass üíæ
 ‚Ä¢ Joining worker nodes üöú  ...
 ‚úì Joining worker nodes üöú
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info
Files changed in python folder:
SKIPPING PYTHON IMAGE BUILD...
Files changed in operator folder:
operator/PROJECT
operator/api/v1/groupversion_info.go
operator/api/v1/seldondeployment_types.go
operator/api/v1/seldondeployment_webhook.go
operator/api/v1/zz_generated.deepcopy.go
operator/api/v1alpha3/groupversion_info.go
operator/api/v1alpha3/seldondeployment_types.go
operator/api/v1alpha3/seldondeployment_webhook.go
operator/api/v1alpha3/zz_generated.deepcopy.go
operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
operator/config/webhook/manifests.yaml
operator/controllers/ambassador.go
operator/controllers/ambassador_test.go
operator/controllers/controller_utils.go
operator/controllers/noengine_test.go
operator/controllers/seldondeployment_controller.go
operator/controllers/seldondeployment_controller_test.go
operator/controllers/seldondeployment_engine.go
operator/controllers/seldondeployment_explainers.go
operator/controllers/seldondeployment_prepackaged_servers.go
operator/controllers/seldondeployment_prepackaged_servers_test.go
operator/controllers/suite_test.go
operator/main.go
operator/utils/utils.go
cd ../../operator && make kind-image-install
make[1]: Entering directory '/workspace/source/operator'
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
go: finding sigs.k8s.io v0.2.0
go: finding sigs.k8s.io/controller-tools/cmd/controller-gen v0.2.0
go: finding sigs.k8s.io/controller-tools/cmd v0.2.0
go: finding sigs.k8s.io/controller-tools v0.2.0
go: downloading sigs.k8s.io/controller-tools v0.2.0
go: extracting sigs.k8s.io/controller-tools v0.2.0
go: downloading k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d
go: downloading k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
go: downloading github.com/spf13/cobra v0.0.3
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/gobuffalo/flect v0.1.5
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading golang.org/x/tools v0.0.0-20190501045030-23463209683d
go: extracting github.com/fatih/color v1.7.0
go: extracting sigs.k8s.io/yaml v1.1.0
go: extracting github.com/gobuffalo/flect v0.1.5
go: downloading k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/mattn/go-isatty v0.0.8
go: extracting github.com/spf13/cobra v0.0.3
go: extracting github.com/mattn/go-colorable v0.1.2
go: downloading gopkg.in/yaml.v2 v2.2.2
go: extracting github.com/mattn/go-isatty v0.0.8
go: downloading golang.org/x/sys v0.0.0-20190621203818-d432491b9138
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: extracting gopkg.in/yaml.v2 v2.2.2
go: extracting github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.3
go: extracting k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d
go: extracting github.com/spf13/pflag v1.0.3
go: extracting k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading k8s.io/klog v0.3.3
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/google/gofuzz v1.0.0
go: extracting k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: extracting gopkg.in/inf.v0 v0.9.1
go: extracting k8s.io/klog v0.3.3
go: extracting github.com/google/gofuzz v1.0.0
go: extracting golang.org/x/tools v0.0.0-20190501045030-23463209683d
go: extracting golang.org/x/sys v0.0.0-20190621203818-d432491b9138
go: extracting github.com/gogo/protobuf v1.2.1
go: extracting golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: downloading golang.org/x/text v0.3.2
go: extracting golang.org/x/text v0.3.2
go: finding github.com/spf13/cobra v0.0.3
go: finding k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
go: finding github.com/fatih/color v1.7.0
go: finding golang.org/x/tools v0.0.0-20190501045030-23463209683d
go: finding github.com/gobuffalo/flect v0.1.5
go: finding k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d
go: finding k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
go: finding sigs.k8s.io/yaml v1.1.0
go: finding github.com/spf13/pflag v1.0.3
go: finding github.com/mattn/go-colorable v0.1.2
go: finding github.com/mattn/go-isatty v0.0.8
go: finding github.com/gogo/protobuf v1.2.1
go: finding github.com/google/gofuzz v1.0.0
go: finding gopkg.in/inf.v0 v0.9.1
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding k8s.io/klog v0.3.3
go: finding golang.org/x/sys v0.0.0-20190621203818-d432491b9138
go: finding golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: finding golang.org/x/text v0.3.2
/builder/home/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
go fmt ./...
go vet ./...
go: downloading github.com/onsi/gomega v1.5.0
go: downloading sigs.k8s.io/testing_frameworks v0.1.1
go: downloading github.com/onsi/ginkgo v1.8.0
go: downloading github.com/gophercloud/gophercloud v0.4.0
go: downloading github.com/Azure/go-autorest/autorest v0.9.2
go: extracting sigs.k8s.io/testing_frameworks v0.1.1
go: extracting github.com/Azure/go-autorest/autorest v0.9.2
go: downloading github.com/Azure/go-autorest/autorest/adal v0.7.0
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: downloading github.com/Azure/go-autorest/tracing v0.5.0
go: extracting github.com/onsi/gomega v1.5.0
go: extracting github.com/Azure/go-autorest/autorest/adal v0.7.0
go: extracting github.com/onsi/ginkgo v1.8.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/hpcloud/tail v1.0.0
go: extracting github.com/Azure/go-autorest/logger v0.1.0
go: extracting github.com/Azure/go-autorest/tracing v0.5.0
go: extracting github.com/Azure/go-autorest/autorest/date v0.2.0
go: extracting github.com/hpcloud/tail v1.0.0
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: extracting gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: extracting github.com/gophercloud/gophercloud v0.4.0
go: finding github.com/onsi/ginkgo v1.8.0
go: finding github.com/onsi/gomega v1.5.0
go: finding sigs.k8s.io/testing_frameworks v0.1.1
go: finding github.com/gophercloud/gophercloud v0.4.0
go: finding github.com/Azure/go-autorest/autorest v0.9.2
go: finding github.com/Azure/go-autorest/autorest/adal v0.7.0
go: finding github.com/hpcloud/tail v1.0.0
go: finding github.com/Azure/go-autorest/tracing v0.5.0
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/Azure/go-autorest/autorest/date v0.2.0
go: finding github.com/Azure/go-autorest/logger v0.1.0
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
/builder/home/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
go test ./... -coverprofile cover.out
?   	github.com/seldonio/seldon-core/operator	[no test files]
?   	github.com/seldonio/seldon-core/operator/api/v1	[no test files]
?   	github.com/seldonio/seldon-core/operator/api/v1alpha2	[no test files]
?   	github.com/seldonio/seldon-core/operator/api/v1alpha3	[no test files]
?   	github.com/seldonio/seldon-core/operator/constants	[no test files]
ok  	github.com/seldonio/seldon-core/operator/controllers	9.238s	coverage: 45.9% of statements
?   	github.com/seldonio/seldon-core/operator/controllers/resources/credentials	[no test files]
ok  	github.com/seldonio/seldon-core/operator/controllers/resources/credentials/gcs	0.013s	coverage: 100.0% of statements
ok  	github.com/seldonio/seldon-core/operator/controllers/resources/credentials/s3	0.011s	coverage: 94.6% of statements
?   	github.com/seldonio/seldon-core/operator/utils	[no test files]
docker build . -t seldonio/seldon-core-operator:0.5.2-SNAPSHOT
Sending build context to Docker daemon  1.017MB
Step 1/15 : FROM golang:1.12.5 as builder
1.12.5: Pulling from library/golang
6f2f362378c5: Pulling fs layer
494c27a8a6b8: Pulling fs layer
7596bb83081b: Pulling fs layer
372744b62d49: Pulling fs layer
0658c6765517: Pulling fs layer
dbd5b1749350: Pulling fs layer
ca642e59c356: Pulling fs layer
372744b62d49: Waiting
0658c6765517: Waiting
ca642e59c356: Waiting
dbd5b1749350: Waiting
7596bb83081b: Download complete
494c27a8a6b8: Verifying Checksum
494c27a8a6b8: Download complete
6f2f362378c5: Verifying Checksum
6f2f362378c5: Download complete
372744b62d49: Verifying Checksum
372744b62d49: Download complete
ca642e59c356: Verifying Checksum
ca642e59c356: Download complete
0658c6765517: Verifying Checksum
0658c6765517: Download complete
dbd5b1749350: Verifying Checksum
dbd5b1749350: Download complete
6f2f362378c5: Pull complete
494c27a8a6b8: Pull complete
7596bb83081b: Pull complete
372744b62d49: Pull complete
0658c6765517: Pull complete
dbd5b1749350: Pull complete
ca642e59c356: Pull complete
Digest: sha256:5bc207d20bd9e97c57dc2ad013f2b02d982cc6e411d48bdc79d90bb601696650
Status: Downloaded newer image for golang:1.12.5
 ---> 1ef078f0da9e
Step 2/15 : WORKDIR /workspace
 ---> Running in 8c4eec8a3b97
Removing intermediate container 8c4eec8a3b97
 ---> 6497041fe764
Step 3/15 : COPY go.mod go.mod
 ---> 207e58565bad
Step 4/15 : COPY go.sum go.sum
 ---> ee2f2acda9fc
Step 5/15 : RUN go mod download
 ---> Running in 0c936158c2cd
[91mgo: finding github.com/gophercloud/gophercloud v0.4.0
go: finding github.com/onsi/ginkgo v1.8.0
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/adal v0.7.0
[0m[91mgo: finding github.com/Azure/go-autorest/autorest v0.9.2
[0m[91mgo: finding github.com/googleapis/gnostic v0.3.0
[0m[91mgo: finding golang.org/x/sys v0.0.0-20190621203818-d432491b9138
go: finding k8s.io/kube-openapi v0.0.0-20190603182131-db7b694dc208
[0m[91mgo: finding sigs.k8s.io/controller-runtime v0.2.0
[0m[91mgo: finding knative.dev/pkg v0.0.0-20190823221514-39a29cf1bf26
[0m[91mgo: finding gopkg.in/yaml.v2 v2.2.2
[0m[91mgo: finding k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
[0m[91mgo: finding github.com/google/gofuzz v1.0.0
[0m[91mgo: finding k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible
[0m[91mgo: finding k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d
[0m[91mgo: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[0m[91mgo: finding sigs.k8s.io/structured-merge-diff v0.0.0-20190525122527-15d366b2352e
[0m[91mgo: finding github.com/gogo/protobuf v1.1.1
[0m[91mgo: finding github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
[0m[91mgo: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
[0m[91mgo: finding github.com/go-openapi/swag v0.0.0-20160704191624-1d0bd113de87
[0m[91mgo: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
[0m[91mgo: finding github.com/davecgh/go-spew v0.0.0-20151105211317-5215b55f46b2
[0m[91mgo: finding github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273
[0m[91mgo: finding github.com/google/gofuzz v0.0.0-20161122191042-44d81051d367
[0m[91mgo: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
[0m[91mgo: finding gopkg.in/yaml.v2 v2.2.1
[0m[91mgo: finding github.com/go-openapi/spec v0.0.0-20160808142527-6aced65f8501
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/date v0.2.0
[0m[91mgo: finding k8s.io/utils v0.0.0-20190506122338-8fab8cb257d5
[0m[91mgo: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58
[0m[91mgo: finding github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
[0m[91mgo: finding go.uber.org/atomic v1.3.2
[0m[91mgo: finding k8s.io/gengo v0.0.0-20190128074634-0689ccc1d7d6
[0m[91mgo: finding github.com/PuerkitoBio/purell v1.0.0
[0m[91mgo: finding golang.org/x/net v0.0.0-20190620200207-3b0461eec859
[0m[91mgo: finding go.uber.org/multierr v1.1.0
[0m[91mgo: finding golang.org/x/sys v0.0.0-20190209173611-3b5209105503
[0m[91mgo: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
[0m[91mgo: finding github.com/googleapis/gnostic v0.0.0-20170426233943-68f4ded48ba9
[0m[91mgo: finding github.com/munnerz/goautoneg v0.0.0-20120707110453-a547fc61f48d
[0m[91mgo: finding gopkg.in/fsnotify.v1 v1.4.7
[0m[91mgo: finding github.com/spf13/afero v1.2.2
[0m[91mgo: finding github.com/ghodss/yaml v0.0.0-20150909031657-73d445a93680
[0m[91mgo: finding sigs.k8s.io/controller-tools v0.2.0
[0m[91mgo: finding github.com/PuerkitoBio/urlesc v0.0.0-20160726150825-5bd2802263f2
[0m[91mgo: finding github.com/go-logr/logr v0.1.0
[0m[91mgo: finding github.com/pborman/uuid v0.0.0-20170612153648-e790cca94e6c
[0m[91mgo: finding golang.org/x/text v0.0.0-20160726164857-2910a502d2bf
[0m[91mgo: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
[0m[91mgo: finding github.com/json-iterator/go v1.1.5
[0m[91mgo: finding github.com/emicklei/go-restful v0.0.0-20170410110728-ff4f55a20633
[0m[91mgo: finding gopkg.in/inf.v0 v0.9.1
[0m[91mgo: finding github.com/Azure/go-autorest/tracing v0.5.0
[0m[91mgo: finding github.com/gogo/protobuf v1.2.1
[0m[91mgo: finding github.com/onsi/gomega v1.4.2
[0m[91mgo: finding cloud.google.com/go v0.26.0
[0m[91mgo: finding gomodules.xyz/jsonpatch/v2 v2.0.1
[0m[91mgo: finding github.com/stretchr/testify v1.3.0
[0m[91mgo: finding github.com/google/go-cmp v0.3.0
[0m[91mgo: finding golang.org/x/sys v0.0.0-20170830134202-bb24a47a89ea
[0m[91mgo: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
[0m[91mgo: finding github.com/Azure/go-autorest/logger v0.1.0
[0m[91mgo: finding k8s.io/klog v0.3.0
[0m[91mgo: finding github.com/stretchr/testify v0.0.0-20151208002404-e3a8ff8ce365
[0m[91mgo: finding github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
[0m[91mgo: finding github.com/go-openapi/jsonreference v0.0.0-20160704190145-13c6e3589ad9
[0m[91mgo: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
[0m[91mgo: finding golang.org/x/crypto v0.0.0-20190211182817-74369b46fc67
[0m[91mgo: finding golang.org/x/crypto v0.0.0-20190611184440-5c40567a22f8
[0m[91mgo: finding github.com/gobuffalo/flect v0.1.5
[0m[91mgo: finding golang.org/x/tools v0.0.0-20181011042414-1f849cf54d09
[0m[91mgo: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
[0m[91mgo: finding github.com/evanphx/json-patch v4.5.0+incompatible
[0m[91mgo: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
[0m[91mgo: finding github.com/prometheus/client_golang v0.9.0
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/adal v0.5.0
[0m[91mgo: finding github.com/golang/protobuf v1.3.1
[0m[91mgo: finding github.com/spf13/pflag v1.0.2
[0m[91mgo: finding golang.org/x/text v0.3.2
[0m[91mgo: finding github.com/modern-go/reflect2 v1.0.1
[0m[91mgo: finding golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
[0m[91mgo: finding github.com/kr/pretty v0.1.0
[0m[91mgo: finding sigs.k8s.io/testing_frameworks v0.1.1
[0m[91mgo: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
[0m[91mgo: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
[0m[91mgo: finding github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
[0m[91mgo: finding github.com/davecgh/go-spew v1.1.0
[0m[91mgo: finding k8s.io/klog v0.3.3
[0m[91mgo: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
[0m[91mgo: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
[0m[91mgo: finding golang.org/x/net v0.0.0-20170114055629-f2499483f923
[0m[91mgo: finding github.com/NYTimes/gziphandler v0.0.0-20170623195520-56545f4a5d46
[0m[91mgo: finding github.com/go-logr/zapr v0.1.0
[0m[91mgo: finding github.com/googleapis/gnostic v0.2.0
[0m[91mgo: finding github.com/modern-go/reflect2 v0.0.0-20180320133207-05fbef0ca5da
[0m[91mgo: finding github.com/onsi/gomega v0.0.0-20170829124025-dcabb60a477c
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/date v0.1.0
[0m[91mgo: finding github.com/stretchr/ob** v0.1.0
[0m[91mgo: finding github.com/onsi/ginkgo v0.0.0-20170829012221-11459a886d9c
[0m[91mgo: finding github.com/golang/protobuf v0.0.0-20161109072736-4bd1920723d7
[0m[91mgo: finding github.com/Azure/go-autorest/autorest v0.9.0
[0m[91mgo: finding go.uber.org/zap v1.9.1
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/mocks v0.3.0
[0m[91mgo: finding github.com/mailru/easyjson v0.0.0-20160728113105-d5b7844b561a
[0m[91mgo: finding github.com/kr/text v0.1.0
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/mocks v0.2.0
[0m[91mgo: finding github.com/mattn/go-colorable v0.1.2
[0m[91mgo: finding github.com/pmezard/go-difflib v1.0.0
[0m[91mgo: finding golang.org/x/text v0.3.0
[0m[91mgo: finding github.com/inconshreveable/mousetrap v1.0.0
[0m[91mgo: finding github.com/kisielk/errcheck v1.1.0
[0m[91mgo: finding github.com/imdario/mergo v0.3.6
[0m[91mgo: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
[0m[91mgo: finding github.com/json-iterator/go v1.1.6
[0m[91mgo: finding github.com/onsi/ginkgo v1.6.0
[0m[91mgo: finding k8s.io/kube-openapi v0.0.0-20180731170545-e3762e86a74c
[0m[91mgo: finding github.com/spf13/pflag v1.0.3
[0m[91mgo: finding github.com/spf13/pflag v0.0.0-20170130214245-9ff6c6923cff
[0m[91mgo: finding github.com/pkg/errors v0.8.1
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/mocks v0.1.0
[0m[91mgo: finding golang.org/x/sys v0.0.0-20190429190828-d89cdac9e872
[0m[91mgo: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
[0m[91mgo: finding k8s.io/klog v0.0.0-20181102134211-b9b56d5dfc92
[0m[91mgo: finding github.com/hpcloud/tail v1.0.0
[0m[91mgo: finding github.com/fsnotify/fsnotify v1.4.7
[0m[91mgo: finding github.com/go-openapi/jsonpointer v0.0.0-20160704185906-46af16f9f7b1
[0m[91mgo: finding github.com/spf13/cobra v0.0.3
[0m[91mgo: finding github.com/kisielk/gotool v1.0.0
[0m[91mgo: finding golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e
[0m[91mgo: finding golang.org/x/tools v0.0.0-20180221164845-07fd8470d635
[0m[91mgo: finding github.com/fatih/color v1.7.0
[0m[91mgo: finding github.com/pmezard/go-difflib v0.0.0-20151028094244-d8ed2627bdf0
[0m[91mgo: finding google.golang.org/appengine v1.1.0
[0m[91mgo: finding golang.org/x/tools v0.0.0-20190501045030-23463209683d
[0m[91mgo: finding github.com/davecgh/go-spew v1.1.1
[0m[91mgo: finding golang.org/x/crypto v0.0.0-20180820150726-614d502a4dac
[0m[91mgo: finding k8s.io/klog v0.2.0
[0m[91mgo: finding github.com/onsi/gomega v1.5.0
[0m[91mgo: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
[0m[91mgo: finding github.com/mattn/go-isatty v0.0.8
[0m[91mgo: finding github.com/golang/protobuf v1.2.0
[0m[91mgo: finding golang.org/x/net v0.0.0-20190501004415-9ce7a6920f09
[0m[91mgo: finding github.com/json-iterator/go v0.0.0-20180612202835-f2b4162afba3
[0m[91mgo: finding k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
[0m[91mgo: finding github.com/kr/pty v1.1.1
[0m[91mgo: finding sigs.k8s.io/yaml v1.1.0
[0m[91mgo: finding github.com/google/go-cmp v0.3.1
[0m[91mgo: finding github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e
[0m[91mgo: finding golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
[0mRemoving intermediate container 0c936158c2cd
 ---> b107a04575cd
Step 6/15 : COPY main.go main.go
 ---> 91744dbf89c2
Step 7/15 : COPY api/ api/
 ---> 169fffeee357
Step 8/15 : COPY controllers/ controllers/
 ---> db8e8d327d8d
Step 9/15 : COPY utils/ utils/
 ---> c96a7616e006
Step 10/15 : COPY constants/ constants/
 ---> a88f1ea487f6
Step 11/15 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go
 ---> Running in c47862d285e3
Removing intermediate container c47862d285e3
 ---> 252be44be7d0
Step 12/15 : FROM gcr.io/distroless/static:latest
latest: Pulling from distroless/static
9ff2acc3204b: Pulling fs layer
9ff2acc3204b: Verifying Checksum
9ff2acc3204b: Download complete
9ff2acc3204b: Pull complete
Digest: sha256:c6d5981545ce1406d33e61434c61e9452dad93ecd8397c41e89036ef977a88f4
Status: Downloaded newer image for gcr.io/distroless/static:latest
 ---> e4d2a899b1bf
Step 13/15 : WORKDIR /
 ---> Running in 8e72f69bc9a4
Removing intermediate container 8e72f69bc9a4
 ---> b4592afae6c6
Step 14/15 : COPY --from=builder /workspace/manager .
 ---> 50aca73f4fda
Step 15/15 : ENTRYPOINT ["/manager"]
 ---> Running in 8585da52ba2f
Removing intermediate container 8585da52ba2f
 ---> 2683b2c9b849
Successfully built 2683b2c9b849
Successfully tagged seldonio/seldon-core-operator:0.5.2-SNAPSHOT
docker save seldonio/seldon-core-operator:0.5.2-SNAPSHOT > operator.tar
kind load image-archive operator.tar --loglevel trace
time="21:01:42" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
time="21:01:42" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}} --filter label=io.k8s.sigs.kind.cluster=kind]"
time="21:01:42" level=debug msg="Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels \"io.k8s.sigs.kind.role\"}} kind-worker]"
time="21:01:43" level=debug msg="Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels \"io.k8s.sigs.kind.role\"}} kind-control-plane]"
time="21:01:43" level=debug msg="Running: /usr/bin/docker [docker exec --privileged -i kind-worker ctr --namespace=k8s.io images import -]"
time="21:01:43" level=debug msg="Running: /usr/bin/docker [docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -]"
make[1]: Leaving directory '/workspace/source/operator'
Files changed in engine folder:
SKIPPING ENGINE IMAGE BUILD...
kubectl create namespace seldon || echo "Namespace seldon already exists"
namespace/seldon created
kubectl create namespace test1 || echo "Namespace test1 already exists"
namespace/test1 created
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
"stable" has been added to your repositories
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ‚éà Happy Helming!‚éà 
helm install ambassador stable/ambassador -f ambassador_values.yaml --set crds.keep=false --namespace seldon --set replicaCount=1
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
NAME: ambassador
LAST DEPLOYED: Wed Dec 11 21:01:54 2019
NAMESPACE: seldon
STATUS: deployed
REVISION: 1
NOTES:
Congratulations! You've successfully installed Ambassador.

For help, visit our Slack at https://d6e.co/slack or view the documentation online at https://www.getambassador.io.

To get the IP address of Ambassador, run the following commands:
  export NODE_PORT=$(kubectl get --namespace seldon -o jsonpath="{.spec.ports[0].nodePort}" services ambassador)
  export NODE_IP=$(kubectl get nodes --namespace seldon -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT
kubectl rollout status deployment.apps/ambassador --namespace seldon
Waiting for deployment "ambassador" rollout to finish: 0 of 1 updated replicas are available...
deployment "ambassador" successfully rolled out
cd ../../operator && make install-cert-manager
make[1]: Entering directory '/workspace/source/operator'
kubectl create namespace cert-manager || echo "Namespace cert-manager-exists"
namespace/cert-manager created
kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true || echo "namespace cert-manager-already labelled"
namespace/cert-manager labeled
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.9.1/cert-manager.yaml
customresourcedefinition.apiextensions.k8s.io/certificates.certmanager.k8s.io created
customresourcedefinition.apiextensions.k8s.io/certificaterequests.certmanager.k8s.io created
customresourcedefinition.apiextensions.k8s.io/challenges.certmanager.k8s.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.certmanager.k8s.io created
customresourcedefinition.apiextensions.k8s.io/issuers.certmanager.k8s.io created
customresourcedefinition.apiextensions.k8s.io/orders.certmanager.k8s.io created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
namespace/cert-manager configured
serviceaccount/cert-manager-cainjector created
serviceaccount/cert-manager-webhook created
serviceaccount/cert-manager created
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrole.rbac.authorization.k8s.io/cert-manager-leaderelection created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-leaderelection created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrole.rbac.authorization.k8s.io/cert-manager-view created
clusterrole.rbac.authorization.k8s.io/cert-manager-edit created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:auth-delegator created
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:webhook-authentication-reader created
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:webhook-requester created
service/cert-manager-webhook created
deployment.apps/cert-manager-cainjector created
deployment.apps/cert-manager-webhook created
deployment.apps/cert-manager created
apiservice.apiregistration.k8s.io/v1beta1.admission.certmanager.k8s.io created
issuer.certmanager.k8s.io/cert-manager-webhook-selfsign created
certificate.certmanager.k8s.io/cert-manager-webhook-ca created
issuer.certmanager.k8s.io/cert-manager-webhook-ca created
certificate.certmanager.k8s.io/cert-manager-webhook-webhook-tls created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
kubectl rollout status deployment.apps/cert-manager -n cert-manager
Waiting for deployment "cert-manager" rollout to finish: 0 of 1 updated replicas are available...
deployment "cert-manager" successfully rolled out
kubectl rollout status deployment.apps/cert-manager-cainjector -n cert-manager
deployment "cert-manager-cainjector" successfully rolled out
kubectl rollout status deployment.apps/cert-manager-webhook -n cert-manager
Waiting for deployment "cert-manager-webhook" rollout to finish: 0 of 1 updated replicas are available...
deployment "cert-manager-webhook" successfully rolled out
make[1]: Leaving directory '/workspace/source/operator'
cd ../../operator && make install deploy
make[1]: Entering directory '/workspace/source/operator'
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
go: finding sigs.k8s.io/controller-tools/cmd/controller-gen v0.2.0
go: finding sigs.k8s.io/controller-tools/cmd v0.2.0
go: finding sigs.k8s.io v0.2.0
/builder/home/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/seldondeployments.machinelearning.seldon.io created
cd config/manager && kustomize edit set image controller=seldonio/seldon-core-operator:0.5.2-SNAPSHOT
kustomize build config/default | kubectl apply -f -
namespace/seldon-system created
customresourcedefinition.apiextensions.k8s.io/seldondeployments.machinelearning.seldon.io configured
mutatingwebhookconfiguration.admissionregistration.k8s.io/seldon-mutating-webhook-configuration created
serviceaccount/seldon-manager created
role.rbac.authorization.k8s.io/seldon-leader-election-role created
role.rbac.authorization.k8s.io/seldon-manager-cm-role created
clusterrole.rbac.authorization.k8s.io/seldon-manager-role created
clusterrole.rbac.authorization.k8s.io/seldon-manager-sas-role created
rolebinding.rbac.authorization.k8s.io/seldon-leader-election-rolebinding created
rolebinding.rbac.authorization.k8s.io/seldon-manager-cm-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/seldon-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/seldon-manager-sas-rolebinding created
configmap/seldon-config created
service/seldon-webhook-service created
deployment.apps/seldon-controller-manager created
certificate.certmanager.k8s.io/seldon-serving-cert created
issuer.certmanager.k8s.io/seldon-selfsigned-issuer created
validatingwebhookconfiguration.admissionregistration.k8s.io/seldon-validating-webhook-configuration created
make[1]: Leaving directory '/workspace/source/operator'
kubectl config set-context $(kubectl config current-context) --namespace=seldon
Context "kubernetes-*****@kind" modified.
make: Entering directory '/workspace/source/python'
pip install -e . -r requirements-dev.txt
Obtaining file:///workspace/source/python
Collecting Flask<2.0.0
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting Flask-cors<4.0.0
  Downloading https://files.pythonhosted.org/packages/78/38/e68b11daa5d613e3a91e4bf3da76c94ac9ee0d9cd515af9c1ab80d36f709/Flask_Cors-3.0.8-py2.py3-none-any.whl
Collecting redis<4.0.0
  Downloading https://files.pythonhosted.org/packages/32/ae/28613a62eea0d53d3db3147f8715f90da07667e99baeedf1010eb400f8c0/redis-3.3.11-py2.py3-none-any.whl (66kB)
Collecting requests<3.0.0
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting numpy<2.0.0
  Downloading https://files.pythonhosted.org/packages/d2/ab/43e678759326f728de861edbef34b8e2ad1b1490505f20e0d1f0716c3bf4/numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl (20.0MB)
Collecting flatbuffers<2.0.0
  Downloading https://files.pythonhosted.org/packages/c9/84/adf5837f96c39990bc55afdfddf460b38b4562f50341359afa32e4a98de7/flatbuffers-1.11-py2.py3-none-any.whl
Requirement already satisfied: protobuf<4.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (3.11.1)
Requirement already satisfied: grpcio<2.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (1.25.0)
Collecting Flask-OpenTracing<1.2.0,>=1.1.0
  Downloading https://files.pythonhosted.org/packages/58/6c/6417701ba5ecc8854670c6db3207bcc3e5fbc96289a7cb18d5516d99a1c6/Flask-OpenTracing-1.1.0.tar.gz
Collecting opentracing<2.3.0,>=2.2.0
  Downloading https://files.pythonhosted.org/packages/94/9f/289424136addf621fb4c75624ef9a3a80e8575da3993a87950c57e93217e/opentracing-2.2.0.tar.gz (47kB)
Collecting jaeger-client<4.2.0,>=4.1.0
  Downloading https://files.pythonhosted.org/packages/f1/da/569a4f1bc3d0c412c7f903053f09ef62fa10949374ca90bc852b22dd3860/jaeger-client-4.1.0.tar.gz (80kB)
Collecting grpcio-opentracing<1.2.0,>=1.1.4
  Downloading https://files.pythonhosted.org/packages/db/82/2fcad380697c3dab25de76ee590bcab3eb9bbfb4add916044d7e83ec2b10/grpcio_opentracing-1.1.4-py3-none-any.whl
Collecting pyaml<20.0.0
  Downloading https://files.pythonhosted.org/packages/35/1e/eda9fe07f752ced7afcef590e7d74390f0d9c9c0b7ff98317afbaa0697e3/pyaml-19.12.0-py2.py3-none-any.whl
Collecting gunicorn<20.1.0,>=19.9.0
  Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
Collecting minio<6.0.0,>=4.0.9
  Downloading https://files.pythonhosted.org/packages/14/46/60bff78df1b112cc50f95c5ffb2e14aaf9aa279a5219845b55c56f214383/minio-5.0.5-py2.py3-none-any.whl (62kB)
Collecting azure-storage-blob<3.0.0,>=2.0.1
  Downloading https://files.pythonhosted.org/packages/3e/84/610f379b46d7d3c2d48eadeed6a12b6d46a43100fea70534f5992d0ac996/azure_storage_blob-2.1.0-py2.py3-none-any.whl (88kB)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 17)) (42.0.2)
Collecting pandas==0.25.3
  Downloading https://files.pythonhosted.org/packages/52/3f/f6a428599e0d4497e1595030965b5ba455fd8ade6e977e3c819973c4b41d/pandas-0.25.3-cp36-cp36m-manylinux1_x86_64.whl (10.4MB)
Collecting google-cloud-storage>=1.16.0
  Downloading https://files.pythonhosted.org/packages/87/78/7cf94b3d0961b1a3036ba351c7fdc04170baa73d20fcb41240da214c83fd/google_cloud_storage-1.23.0-py2.py3-none-any.whl (72kB)
Collecting mypy<0.751
  Downloading https://files.pythonhosted.org/packages/af/18/4732e5693f56cc0f6dde54428c4d012354e3d7bc7c962b2b5b8b15e2bf06/mypy-0.750-cp36-cp36m-manylinux1_x86_64.whl (23.9MB)
Collecting pytest<6.0.0
  Downloading https://files.pythonhosted.org/packages/da/ed/d22d7f06eb1107271694ed2171b9d52e8eea38d9757124e75ba13324ac77/pytest-5.3.1-py3-none-any.whl (233kB)
Collecting pytest-cov<3.0.0
  Downloading https://files.pythonhosted.org/packages/b9/54/3673ee8be482f81527678ac894276223b9814bb7262e4f730469bb7bf70e/pytest_cov-2.8.1-py2.py3-none-any.whl
Collecting Pillow==6.2.0
  Downloading https://files.pythonhosted.org/packages/19/66/6113477dc3206ccb1e192cffd626f2840ead02375a6cebe2436ad4c19f61/Pillow-6.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
Collecting tox<4.0.0
  Downloading https://files.pythonhosted.org/packages/a7/64/73ee95a48a69fb40f9ce415cdeda09c0c2721da483aae0687884f3cb0586/tox-3.14.2-py2.py3-none-any.whl (80kB)
Collecting Jinja2>=2.10.1
  Downloading https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl (125kB)
Collecting click>=5.1
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting itsdangerous>=0.24
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.15
  Downloading https://files.pythonhosted.org/packages/ce/42/3aeda98f96e85fd26180534d36570e4d18108d62ae36f87694b476b83d6f/Werkzeug-0.16.0-py2.py3-none-any.whl (327kB)
Requirement already satisfied: Six in /usr/local/lib/python3.6/site-packages (from Flask-cors<4.0.0->-r requirements.txt (line 2)) (1.13.0)
Collecting idna<2.9,>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Collecting chardet<3.1.0,>=3.0.2
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
Collecting threadloop<2,>=1
  Downloading https://files.pythonhosted.org/packages/d3/1d/8398c1645b97dc008d3c658e04beda01ede3d90943d40c8d56863cf891bd/threadloop-1.0.2.tar.gz
Collecting thrift
  Downloading https://files.pythonhosted.org/packages/97/1e/3284d19d7be99305eda145b8aa46b0c33244e4a496ec66440dac19f8274d/thrift-0.13.0.tar.gz (59kB)
Collecting tornado<6,>=4.3
  Downloading https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz (516kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/site-packages (from pyaml<20.0.0->-r requirements.txt (line 13)) (5.2)
Collecting python-dateutil
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Collecting pytz
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
Collecting azure-storage-common~=2.1
  Downloading https://files.pythonhosted.org/packages/6b/a0/6794b318ce0118d1a4053bdf0149a60807407db9b710354f2b203c2f5975/azure_storage_common-2.1.0-py2.py3-none-any.whl (47kB)
Collecting azure-common>=1.1.5
  Downloading https://files.pythonhosted.org/packages/00/55/a703923c12cd3172d5c007beda0c1a34342a17a6a72779f8a7c269af0cd6/azure_common-1.1.23-py2.py3-none-any.whl
Collecting google-cloud-core<2.0dev,>=1.0.3
  Downloading https://files.pythonhosted.org/packages/93/54/8c5542c0df4c8a92c0b8736ee67abc4daa9ff3734a0119310c125673ac79/google_cloud_core-1.1.0-py2.py3-none-any.whl
Collecting google-auth>=1.2.0
  Downloading https://files.pythonhosted.org/packages/b6/48/50934afa81c9ab6d68acc19c1c0543f765699fa4e3a36d675baa97816bb1/google_auth-1.8.1-py2.py3-none-any.whl (75kB)
Collecting google-resumable-media<0.6dev,>=0.5.0
  Downloading https://files.pythonhosted.org/packages/35/9e/f73325d0466ce5bdc36333f1aeb2892ead7b76e79bdb5c8b0493961fa098/google_resumable_media-0.5.0-py2.py3-none-any.whl
Collecting typing-extensions>=3.7.4
  Downloading https://files.pythonhosted.org/packages/03/92/705fe8aca27678e01bbdd7738173b8e7df0088a2202c80352f664630d638/typing_extensions-3.7.4.1-py3-none-any.whl
Collecting typed-ast<1.5.0,>=1.4.0
  Downloading https://files.pythonhosted.org/packages/31/d3/9d1802c161626d0278bafb1ffb32f76b9d01e123881bbf9d91e8ccf28e18/typed_ast-1.4.0-cp36-cp36m-manylinux1_x86_64.whl (736kB)
Collecting mypy-extensions<0.5.0,>=0.4.0
  Downloading https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl
Collecting packaging
  Downloading https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading https://files.pythonhosted.org/packages/e9/71/1a1e0ed0981bb6a67bce55a210f168126b7ebd2065958673797ea66489ca/importlib_metadata-1.3.0-py2.py3-none-any.whl
Collecting py>=1.5.0
  Downloading https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
Collecting pluggy<1.0,>=0.12
  Downloading https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0
  Downloading https://files.pythonhosted.org/packages/68/03/0604cec1ea13c9f063dd50f900d1a36160334dd3cfb01fd0e638f61b46ba/more_itertools-8.0.2-py3-none-any.whl (40kB)
Collecting attrs>=17.4.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting wcwidth
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting coverage>=4.4
  Downloading https://files.pythonhosted.org/packages/51/b1/13609068fff1c8c056f0c4601ad6985cf5c1bbfc529196ab08bd2a57dc39/coverage-4.5.4-cp36-cp36m-manylinux1_x86_64.whl (205kB)
Collecting virtualenv>=16.0.0
  Downloading https://files.pythonhosted.org/packages/62/77/6a86ef945ad39aae34aed4cc1ae4a2f941b9870917a974ed7c5b6f137188/virtualenv-16.7.8-py2.py3-none-any.whl (3.4MB)
Collecting toml>=0.9.4
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting filelock<4,>=3.0.0
  Downloading https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting MarkupSafe>=0.23
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cryptography
  Downloading https://files.pythonhosted.org/packages/ca/9a/7cece52c46546e214e10811b36b2da52ce1ea7fa203203a629b8dfadad53/cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl (2.3MB)
Collecting google-api-core<2.0.0dev,>=1.14.0
  Downloading https://files.pythonhosted.org/packages/29/3a/c528ef37f48d6ffba16f0f3c0426456ba21e0dd32be9c61a2ade93e07faa/google_api_core-1.14.3-py2.py3-none-any.whl (68kB)
Collecting cachetools<3.2,>=2.0.0
  Downloading https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
Collecting rsa<4.1,>=3.1.4
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1
  Downloading https://files.pythonhosted.org/packages/52/50/bb4cefca37da63a0c52218ba2cb1b1c36110d84dcbae8aa48cd67c5e95c2/pyasn1_modules-0.2.7-py2.py3-none-any.whl (131kB)
Collecting pyparsing>=2.0.2
  Downloading https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl (67kB)
Collecting zipp>=0.5
  Downloading https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8
  Downloading https://files.pythonhosted.org/packages/49/72/0d42f94fe94afa8030350c26e9d787219f3f008ec9bf6b86c66532b29236/cffi-1.13.2-cp36-cp36m-manylinux1_x86_64.whl (397kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading https://files.pythonhosted.org/packages/eb/ee/e59e74ecac678a14d6abefb9054f0bbcb318a6452a30df3776f133886d7d/googleapis-common-protos-1.6.0.tar.gz
Collecting pyasn1>=0.1.3
  Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
Collecting pycparser
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Building wheels for collected packages: Flask-OpenTracing, opentracing, jaeger-client, threadloop, thrift, tornado, googleapis-common-protos, pycparser
  Building wheel for Flask-OpenTracing (setup.py): started
  Building wheel for Flask-OpenTracing (setup.py): finished with status 'done'
  Created wheel for Flask-OpenTracing: filename=Flask_OpenTracing-1.1.0-cp36-none-any.whl size=9071 sha256=70415b03fea5ed3644e7294088e1fe3e14d5f32f148c9856950e3c7ca352c896
  Stored in directory: /builder/home/.cache/pip/wheels/7b/dc/25/3cf0b35c129232ee596c413f13d1d1f5a8e38c427266276dfd
  Building wheel for opentracing (setup.py): started
  Building wheel for opentracing (setup.py): finished with status 'done'
  Created wheel for opentracing: filename=opentracing-2.2.0-cp36-none-any.whl size=49320 sha256=0a9b714b3866eacd74057c20d19e2445e73e6a0585ba348af422b06c67d630a2
  Stored in directory: /builder/home/.cache/pip/wheels/93/e9/b5/1cdc3544f99a54caca13832b5afa26fd98701fe709dc049576
  Building wheel for jaeger-client (setup.py): started
  Building wheel for jaeger-client (setup.py): finished with status 'done'
  Created wheel for jaeger-client: filename=jaeger_client-4.1.0-cp36-none-any.whl size=64309 sha256=129f4d0268cb6c8aa3b504d813df378f1a5baaf4f87032e504b32824f354102b
  Stored in directory: /builder/home/.cache/pip/wheels/f2/84/7f/e89da3ee8ce35598d6382b6389fa2ada5d66acca2422537994
  Building wheel for threadloop (setup.py): started
  Building wheel for threadloop (setup.py): finished with status 'done'
  Created wheel for threadloop: filename=threadloop-1.0.2-cp36-none-any.whl size=3425 sha256=92074b0d02d8dca96efaf1ba7bfe08201b0087ac0864653f1b939d64f8572ddb
  Stored in directory: /builder/home/.cache/pip/wheels/d7/7a/30/d212623a4cd34f6cce400f8122b1b7af740d3440c68023d51f
  Building wheel for thrift (setup.py): started
  Building wheel for thrift (setup.py): finished with status 'done'
  Created wheel for thrift: filename=thrift-0.13.0-cp36-cp36m-linux_x86_64.whl size=483877 sha256=9412309f5c13e55a70a10ea3b0055ee46e9febd82006a86c090174a861d7f5a5
  Stored in directory: /builder/home/.cache/pip/wheels/02/a2/46/689ccfcf40155c23edc7cdbd9de488611c8fdf49ff34b1706e
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-5.1.1-cp36-cp36m-linux_x86_64.whl size=462654 sha256=1da468456a3990a3170c7f0d72f149055cc052f5c819c3ab08a36b9dd5355819
  Stored in directory: /builder/home/.cache/pip/wheels/6d/e1/ce/f4ee2fa420cc6b940123c64992b81047816d0a9fad6b879325
  Building wheel for googleapis-common-protos (setup.py): started
  Building wheel for googleapis-common-protos (setup.py): finished with status 'done'
  Created wheel for googleapis-common-protos: filename=googleapis_common_protos-1.6.0-cp36-none-any.whl size=77577 sha256=8ce242d0238cfa97951cd621f2d4183fc986579a674796ce71d640197c708113
  Stored in directory: /builder/home/.cache/pip/wheels/9e/3d/a2/1bec8bb7db80ab3216dbc33092bb7ccd0debfb8ba42b5668d5
  Building wheel for pycparser (setup.py): started
  Building wheel for pycparser (setup.py): finished with status 'done'
  Created wheel for pycparser: filename=pycparser-2.19-py2.py3-none-any.whl size=111029 sha256=94e4c769bdfd1d370628409a0f60a8d086d54f750de4197cdedfb32f4d45bb89
  Stored in directory: /builder/home/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built Flask-OpenTracing opentracing jaeger-client threadloop thrift tornado googleapis-common-protos pycparser
Installing collected packages: MarkupSafe, Jinja2, click, itsdangerous, Werkzeug, Flask, Flask-cors, redis, idna, chardet, certifi, urllib3, requests, numpy, flatbuffers, opentracing, Flask-OpenTracing, tornado, threadloop, thrift, jaeger-client, grpcio-opentracing, pyaml, gunicorn, python-dateutil, pytz, minio, pycparser, cffi, cryptography, azure-common, azure-storage-common, azure-storage-blob, pandas, googleapis-common-protos, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, google-api-core, google-cloud-core, google-resumable-media, google-cloud-storage, typing-extensions, typed-ast, mypy-extensions, mypy, pyparsing, packaging, more-itertools, zipp, importlib-metadata, py, pluggy, attrs, wcwidth, pytest, coverage, pytest-cov, Pillow, virtualenv, toml, filelock, tox, seldon-core
  Running setup.py develop for seldon-core
Successfully installed Flask-1.1.1 Flask-OpenTracing-1.1.0 Flask-cors-3.0.8 Jinja2-2.10.3 MarkupSafe-1.1.1 Pillow-6.2.0 Werkzeug-0.16.0 attrs-19.3.0 azure-common-1.1.23 azure-storage-blob-2.1.0 azure-storage-common-2.1.0 cachetools-3.1.1 certifi-2019.11.28 cffi-1.13.2 chardet-3.0.4 click-7.0 coverage-4.5.4 cryptography-2.8 filelock-3.0.12 flatbuffers-1.11 google-api-core-1.14.3 google-auth-1.8.1 google-cloud-core-1.1.0 google-cloud-storage-1.23.0 google-resumable-media-0.5.0 googleapis-common-protos-1.6.0 grpcio-opentracing-1.1.4 gunicorn-20.0.4 idna-2.8 importlib-metadata-1.3.0 itsdangerous-1.1.0 jaeger-client-4.1.0 minio-5.0.5 more-itertools-8.0.2 mypy-0.750 mypy-extensions-0.4.3 numpy-1.17.4 opentracing-2.2.0 packaging-19.2 pandas-0.25.3 pluggy-0.13.1 py-1.8.0 pyaml-19.12.0 pyasn1-0.4.8 pyasn1-modules-0.2.7 pycparser-2.19 pyparsing-2.4.5 pytest-5.3.1 pytest-cov-2.8.1 python-dateutil-2.8.1 pytz-2019.3 redis-3.3.11 requests-2.22.0 rsa-4.0 seldon-core threadloop-1.0.2 thrift-0.13.0 toml-0.10.0 tornado-5.1.1 tox-3.14.2 typed-ast-1.4.0 typing-extensions-3.7.4.1 urllib3-1.25.7 virtualenv-16.7.8 wcwidth-0.1.7 zipp-0.6.0
make: Leaving directory '/workspace/source/python'
cp ../../proto/prediction.proto ./proto
cd ../../proto/tensorflow && make create_protos
make[1]: Entering directory '/workspace/source/proto/tensorflow'
./create-protos.sh
Downloading proto files for master
make[1]: Leaving directory '/workspace/source/proto/tensorflow'
cp -vr ../../proto/tensorflow/tensorflow .
'../../proto/tensorflow/tensorflow' -> './tensorflow'
'../../proto/tensorflow/tensorflow/core' -> './tensorflow/core'
'../../proto/tensorflow/tensorflow/core/framework' -> './tensorflow/core/framework'
'../../proto/tensorflow/tensorflow/core/framework/types.proto' -> './tensorflow/core/framework/types.proto'
'../../proto/tensorflow/tensorflow/core/framework/resource_handle.proto' -> './tensorflow/core/framework/resource_handle.proto'
'../../proto/tensorflow/tensorflow/core/framework/tensor_shape.proto' -> './tensorflow/core/framework/tensor_shape.proto'
'../../proto/tensorflow/tensorflow/core/framework/tensor.proto' -> './tensorflow/core/framework/tensor.proto'
python -m grpc.tools.protoc -I. --python_out=. --grpc_python_out=. ./proto/prediction.proto
cd ../../notebooks && make build_protos
make[1]: Entering directory '/workspace/source/notebooks'
cd ../proto/tensorflow && make create_protos
make[2]: Entering directory '/workspace/source/proto/tensorflow'
make[2]: Nothing to be done for 'create_protos'.
make[2]: Leaving directory '/workspace/source/proto/tensorflow'
cp -vr ../proto/tensorflow/tensorflow .
'../proto/tensorflow/tensorflow' -> './tensorflow'
'../proto/tensorflow/tensorflow/core' -> './tensorflow/core'
'../proto/tensorflow/tensorflow/core/framework' -> './tensorflow/core/framework'
'../proto/tensorflow/tensorflow/core/framework/types.proto' -> './tensorflow/core/framework/types.proto'
'../proto/tensorflow/tensorflow/core/framework/resource_handle.proto' -> './tensorflow/core/framework/resource_handle.proto'
'../proto/tensorflow/tensorflow/core/framework/tensor_shape.proto' -> './tensorflow/core/framework/tensor_shape.proto'
'../proto/tensorflow/tensorflow/core/framework/tensor.proto' -> './tensorflow/core/framework/tensor.proto'
cp ../proto/prediction.proto ./proto
python -m grpc.tools.protoc -I. --python_out=. --grpc_python_out=. ./proto/prediction.proto
make[1]: Leaving directory '/workspace/source/notebooks'
cd ../../proto/k8s && make create_protos
make[1]: Entering directory '/workspace/source/proto/k8s'
./create-k8s-protos.sh
Downloading proto files for master
Munging proto file packages
sed -i.bak 's|import "k8s.io/apiextensions-apiserver/|//import "k8s.io/apiextensions-apiserver/|' k8s.io/api/core/v1/generated.proto
rm k8s.io/api/core/v1/generated.proto.bak
make[1]: Leaving directory '/workspace/source/proto/k8s'
pip install -r dev_requirements.txt
Obtaining file:///workspace/source/python (from -r dev_requirements.txt (line 4))
Requirement already satisfied: pytest in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 1)) (5.3.1)
Collecting retrying
  Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
Requirement already satisfied: Flask<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: Flask-cors<4.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (3.0.8)
Requirement already satisfied: redis<4.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (3.3.11)
Requirement already satisfied: requests<3.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.22.0)
Requirement already satisfied: numpy<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.17.4)
Requirement already satisfied: flatbuffers<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.11)
Requirement already satisfied: protobuf<4.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (3.11.1)
Requirement already satisfied: grpcio<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.25.0)
Requirement already satisfied: Flask-OpenTracing<1.2.0,>=1.1.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: opentracing<2.3.0,>=2.2.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: jaeger-client<4.2.0,>=4.1.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (4.1.0)
Requirement already satisfied: grpcio-opentracing<1.2.0,>=1.1.4 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.1.4)
Requirement already satisfied: pyaml<20.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (19.12.0)
Requirement already satisfied: gunicorn<20.1.0,>=19.9.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (20.0.4)
Requirement already satisfied: minio<6.0.0,>=4.0.9 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (5.0.5)
Requirement already satisfied: azure-storage-blob<3.0.0,>=2.0.1 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.1.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (42.0.2)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from pytest->-r dev_requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from pytest->-r dev_requirements.txt (line 1)) (0.1.7)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/site-packages (from pytest->-r dev_requirements.txt (line 1)) (19.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from pytest->-r dev_requirements.txt (line 1)) (19.2)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/site-packages (from pytest->-r dev_requirements.txt (line 1)) (8.0.2)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.6/site-packages (from pytest->-r dev_requirements.txt (line 1)) (0.13.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/site-packages (from pytest->-r dev_requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.6/site-packages (from retrying->-r dev_requirements.txt (line 2)) (1.13.0)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (7.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (0.16.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.10.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: thrift in /usr/local/lib/python3.6/site-packages (from jaeger-client<4.2.0,>=4.1.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (0.13.0)
Requirement already satisfied: tornado<6,>=4.3 in /usr/local/lib/python3.6/site-packages (from jaeger-client<4.2.0,>=4.1.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (5.1.1)
Requirement already satisfied: threadloop<2,>=1 in /usr/local/lib/python3.6/site-packages (from jaeger-client<4.2.0,>=4.1.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/site-packages (from pyaml<20.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (5.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/site-packages (from minio<6.0.0,>=4.0.9->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.8.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from minio<6.0.0,>=4.0.9->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2019.3)
Requirement already satisfied: azure-common>=1.1.5 in /usr/local/lib/python3.6/site-packages (from azure-storage-blob<3.0.0,>=2.0.1->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.1.23)
Requirement already satisfied: azure-storage-common~=2.1 in /usr/local/lib/python3.6/site-packages (from azure-storage-blob<3.0.0,>=2.0.1->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.1.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest->-r dev_requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->pytest->-r dev_requirements.txt (line 1)) (2.4.5)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2>=2.10.1->Flask<2.0.0->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: cryptography in /usr/local/lib/python3.6/site-packages (from azure-storage-common~=2.1->azure-storage-blob<3.0.0,>=2.0.1->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.8)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/site-packages (from cryptography->azure-storage-common~=2.1->azure-storage-blob<3.0.0,>=2.0.1->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (1.13.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography->azure-storage-common~=2.1->azure-storage-blob<3.0.0,>=2.0.1->seldon-core==0.5.1->-r dev_requirements.txt (line 4)) (2.19)
Building wheels for collected packages: retrying
  Building wheel for retrying (setup.py): started
  Building wheel for retrying (setup.py): finished with status 'done'
  Created wheel for retrying: filename=retrying-1.3.3-cp36-none-any.whl size=11429 sha256=24787e22ab9cc67a964fd0cbc61c10014c9efa6c0d4d09791a6bbdf8526ed754
  Stored in directory: /builder/home/.cache/pip/wheels/d7/a9/33/acc7b709e2a35caa7d4cae442f6fe6fbf2c43f80823d46460c
Successfully built retrying
Installing collected packages: retrying, seldon-core
  Found existing installation: seldon-core 0.5.1
    Uninstalling seldon-core-0.5.1:
      Successfully uninstalled seldon-core-0.5.1
  Running setup.py develop for seldon-core
Successfully installed retrying-1.3.3 seldon-core
pip install pytest-xdist
Collecting pytest-xdist
  Downloading https://files.pythonhosted.org/packages/f7/80/2af1fc039f779f61c7207dc9f79a1479874e7795f869fddaf135efde1cd4/pytest_xdist-1.30.0-py2.py3-none-any.whl
Collecting execnet>=1.1
  Downloading https://files.pythonhosted.org/packages/d3/2e/c63af07fa471e0a02d05793c7a56a9f7d274a8489442a5dc4fb3b2b3c705/execnet-1.7.1-py2.py3-none-any.whl
Collecting pytest-forked
  Downloading https://files.pythonhosted.org/packages/03/1e/81235e1fcfed57a4e679d34794d60c01a1e9a29ef5b9844d797716111d80/pytest_forked-1.1.3-py2.py3-none-any.whl
Requirement already satisfied: pytest>=4.4.0 in /usr/local/lib/python3.6/site-packages (from pytest-xdist) (5.3.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from pytest-xdist) (1.13.0)
Collecting apipkg>=1.4
  Downloading https://files.pythonhosted.org/packages/67/08/4815a09603fc800209431bec5b8bd2acf2f95abdfb558a44a42507fb94da/apipkg-1.5-py2.py3-none-any.whl
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from pytest>=4.4.0->pytest-xdist) (19.2)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/site-packages (from pytest>=4.4.0->pytest-xdist) (8.0.2)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.6/site-packages (from pytest>=4.4.0->pytest-xdist) (0.13.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from pytest>=4.4.0->pytest-xdist) (1.3.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/site-packages (from pytest>=4.4.0->pytest-xdist) (1.8.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/site-packages (from pytest>=4.4.0->pytest-xdist) (19.3.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from pytest>=4.4.0->pytest-xdist) (0.1.7)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->pytest>=4.4.0->pytest-xdist) (2.4.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=4.4.0->pytest-xdist) (0.6.0)
Installing collected packages: apipkg, execnet, pytest-forked, pytest-xdist
Successfully installed apipkg-1.5 execnet-1.7.1 pytest-forked-1.1.3 pytest-xdist-1.30.0
# Run the core tests in parallel
pytest \
	--verbose \
	-s \
	-W ignore \
	--ignore test_s2i_python.py \
	-n "4"  2>&1
============================= test session starts ==============================
platform linux -- Python 3.6.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /
plugins: xdist-1.30.0, forked-1.1.3, cov-2.8.1
gw0 I / gw1 I / gw2 I / gw3 I
[gw0] linux Python 3.6.0 cwd: /workspace/source/testing/scripts
[gw1] linux Python 3.6.0 cwd: /workspace/source/testing/scripts
[gw2] linux Python 3.6.0 cwd: /workspace/source/testing/scripts
[gw3] linux Python 3.6.0 cwd: /workspace/source/testing/scripts
[gw0] Python 3.6.0 (default, Dec 10 2019, 10:37:38)  -- [GCC 8.3.0]
[gw1] Python 3.6.0 (default, Dec 10 2019, 10:37:38)  -- [GCC 8.3.0]
[gw2] Python 3.6.0 (default, Dec 10 2019, 10:37:38)  -- [GCC 8.3.0]
[gw3] Python 3.6.0 (default, Dec 10 2019, 10:37:38)  -- [GCC 8.3.0]
gw0 [24] / gw1 [24] / gw2 [24] / gw3 [24]

scheduling tests via LoadScheduling

test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha2] 
test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha3] 
test_bad_graphs.py::TestBadGraphs::test_duplicate_predictor_name 
test_api_version.py::test_api_version[machinelearning.seldon.io/v1] Error from server (SeldonDeployment.machinelearing.seldon.io "dupname" is invalid: [spec.predictors[1]: Invalid value: "mymodel": Duplicate predictor name, spec: Invalid value: "dupname": Traffic must sum to 100 for multiple predictors]): error when creating "../resources/bad_duplicate_predictor_name.json": admission webhook "vseldondeployment.kb.io" denied the request: SeldonDeployment.machinelearing.seldon.io "dupname" is invalid: [spec.predictors[1]: Invalid value: "mymodel": Duplicate predictor name, spec: Invalid value: "dupname": Traffic must sum to 100 for multiple predictors]

[gw3] PASSED test_bad_graphs.py::TestBadGraphs::test_duplicate_predictor_name 
test_helm_charts_clusterwide.py::TestClusterWide::test_mab_model Error from server (NotFound): deployments.extensions "mymodel-mymodel-7cd068f" not found
Error from server (NotFound): deployments.extensions "mymodel-mymodel-7cd068f" not found
Error from server (NotFound): deployments.extensions "mymodel-mymodel-7cd068f" not found
Error from server (NotFound): deployments.extensions "mymab-mymab-41de5b8" not found
Error: uninstall: Release not loaded: mymodel: release: not found
Error: uninstall: Release not loaded: mymab: release: not found
Error: uninstall: Release not loaded: mymodel: release: not found
Error: uninstall: Release not loaded: mymodel: release: not found

[gw2] PASSED test_api_version.py::test_api_version[machinelearning.seldon.io/v1] 
test_helm_charts_clusterwide.py::TestClusterWide::test_abtest_model 
[gw0] PASSED test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha2] 
test_bad_graphs.py::TestBadGraphs::test_model_name_mismatch Error from server (SeldonDeployment.machinelearing.seldon.io "namemismatch" is invalid: spec.predictors[0].graph: Invalid value: "complex-model_bad_name": Can't find container for Predictive Unit): error when creating "../resources/bad_name_mismatch.json": admission webhook "vseldondeployment.kb.io" denied the request: SeldonDeployment.machinelearing.seldon.io "namemismatch" is invalid: spec.predictors[0].graph: Invalid value: "complex-model_bad_name": Can't find container for Predictive Unit

[gw0] PASSED test_bad_graphs.py::TestBadGraphs::test_model_name_mismatch 
test_prepackaged_servers.py::TestPrepack::test_xgboost Error from server (NotFound): deployments.extensions "iris-default-af1783b" not found

[gw1] PASSED test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha3] 
test_helm_charts_clusterwide.py::TestClusterWide::test_single_model 
[gw3] PASSED test_helm_charts_clusterwide.py::TestClusterWide::test_mab_model 
test_prepackaged_servers.py::TestPrepack::test_sklearn Error from server (NotFound): deployments.extensions "iris-default-4903e3c" not found
Error: uninstall: Release not loaded: myabtest: release: not found
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 70, in format
    return super().format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 570, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 333, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1554, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 258, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 239, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 196, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 246, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 70, in pytest_runtestloop
    self.run_one_test(torun)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 87, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 96, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 182, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 234, in from_call
    result = func()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 131, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1435, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 166, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/workspace/source/testing/scripts/test_helm_charts_clusterwide.py", line 26, in test_single_model
    initial_rest_request("mymodel", namespace)
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 134, in initial_rest_request
    names=names,
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 107, in rest_request
    logging.warning("Bad status:", r.status_code)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1855, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1313, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1437, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1447, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1509, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 858, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 301, in emit
    logging.StreamHandler.emit(self, record)
Message: 'Bad status:'
Arguments: (504,)
Error: uninstall: Release not loaded: mymodel: release: not found

[gw1] PASSED test_helm_charts_clusterwide.py::TestClusterWide::test_single_model 
test_rolling_updates.py::TestRollingHttp::test_rolling_update1 
[gw2] PASSED test_helm_charts_clusterwide.py::TestClusterWide::test_abtest_model 
test_prepackaged_servers.py::TestPrepack::test_tfserving 
[gw0] PASSED test_prepackaged_servers.py::TestPrepack::test_xgboost 
test_prepackaged_servers.py::TestPrepack::test_mlflow Error from server (NotFound): deployments.extensions "wines-default-8c791aa" not found

[gw3] PASSED test_prepackaged_servers.py::TestPrepack::test_sklearn 
test_rolling_updates.py::TestRollingHttp::test_rolling_update2 
[gw0] PASSED test_prepackaged_servers.py::TestPrepack::test_mlflow 
test_rolling_updates.py::TestRollingHttp::test_rolling_update5 
[gw2] PASSED test_prepackaged_servers.py::TestPrepack::test_tfserving 
test_rolling_updates.py::TestRollingHttp::test_rolling_update4 Error from server (NotFound): deployments.extensions "mymodel-mymodel-e2eb561" not found
Error from server (NotFound): error when deleting "../resources/graph2.json": seldondeployments.machinelearning.seldon.io "mymodel" not found

[gw0] FAILED test_rolling_updates.py::TestRollingHttp::test_rolling_update5 
test_rolling_updates.py::TestRollingHttp::test_rolling_update7 Error from server (NotFound): error when deleting "../resources/graph3.json": seldondeployments.machinelearning.seldon.io "mymodel" not found

[gw1] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update1 
test_rolling_updates.py::TestRollingHttp::test_rolling_update3 --- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 70, in format
    return super().format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 570, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 333, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1554, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 258, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 239, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 196, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 246, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 70, in pytest_runtestloop
    self.run_one_test(torun)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 87, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 96, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 182, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 234, in from_call
    result = func()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 131, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1435, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 166, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/workspace/source/testing/scripts/test_rolling_updates.py", line 267, in test_rolling_update7
    r = initial_rest_request("mymodel", namespace)
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 134, in initial_rest_request
    names=names,
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 107, in rest_request
    logging.warning("Bad status:", r.status_code)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1855, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1313, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1437, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1447, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1509, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 858, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 301, in emit
    logging.StreamHandler.emit(self, record)
Message: 'Bad status:'
Arguments: (404,)
Error from server (NotFound): error when deleting "../resources/graph5.json": seldondeployments.machinelearning.seldon.io "mymodel" not found

[gw3] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update2 
test_rolling_updates.py::TestRollingHttp::test_rolling_update6 Error from server (NotFound): error when deleting "../resources/graph3svc.json": seldondeployments.machinelearning.seldon.io "mymodel" not found

[gw2] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update4 
test_rolling_updates.py::TestRollingHttp::test_rolling_update8 --- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 70, in format
    return super().format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 570, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 333, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1554, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 258, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 239, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 196, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 246, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 70, in pytest_runtestloop
    self.run_one_test(torun)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 87, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 96, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 182, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 234, in from_call
    result = func()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 131, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1435, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 166, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/workspace/source/testing/scripts/test_rolling_updates.py", line 227, in test_rolling_update6
    r = initial_rest_request("mymodel", namespace)
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 134, in initial_rest_request
    names=names,
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 107, in rest_request
    logging.warning("Bad status:", r.status_code)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1855, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1313, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1437, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1447, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1509, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 858, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 301, in emit
    logging.StreamHandler.emit(self, record)
Message: 'Bad status:'
Arguments: (404,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 70, in format
    return super().format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 570, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 333, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1554, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 258, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 239, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 196, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 246, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 70, in pytest_runtestloop
    self.run_one_test(torun)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 87, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 96, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 182, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 234, in from_call
    result = func()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 131, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1435, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 166, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/workspace/source/testing/scripts/test_rolling_updates.py", line 307, in test_rolling_update8
    r = initial_rest_request("mymodel", namespace)
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 134, in initial_rest_request
    names=names,
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 107, in rest_request
    logging.warning("Bad status:", r.status_code)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1855, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1313, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1437, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1447, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1509, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 858, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 301, in emit
    logging.StreamHandler.emit(self, record)
Message: 'Bad status:'
Arguments: (404,)

[gw0] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update7 
test_rolling_updates.py::TestRollingHttp::test_rolling_update9 Error from server (NotFound): error when deleting "../resources/graph4.json": seldondeployments.machinelearning.seldon.io "mymodel" not found
Error from server (NotFound): error when deleting "../resources/graph2svc.json": seldondeployments.machinelearning.seldon.io "mymodel" not found
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 70, in format
    return super().format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 570, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 333, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1554, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 258, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 239, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 196, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 246, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 73, in pytest_runtestloop
    self.run_one_test(torun)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 87, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 96, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 182, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 234, in from_call
    result = func()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 131, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1435, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 166, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/workspace/source/testing/scripts/test_rolling_updates.py", line 341, in test_rolling_update9
    r = initial_rest_request("mymodel", namespace)
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 134, in initial_rest_request
    names=names,
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 107, in rest_request
    logging.warning("Bad status:", r.status_code)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1855, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1313, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1437, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1447, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1509, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 858, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 301, in emit
    logging.StreamHandler.emit(self, record)
Message: 'Bad status:'
Arguments: (404,)

[gw1] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update3 
test_rolling_updates.py::TestRollingHttp::test_rolling_update10 Error from server (NotFound): deployments.extensions "mymodel-mymodel-svc-orch-8e2a24b" not found

[gw3] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update6 
test_rolling_updates.py::test_rolling_update_deployment[graph1.json-graph8.json] Error from server (NotFound): error when deleting "../resources/graph4svc.json": seldondeployments.machinelearning.seldon.io "mymodel" not found
Error from server (NotFound): error when deleting "../resources/graph5svc.json": seldondeployments.machinelearning.seldon.io "mymodel" not found
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 70, in format
    return super().format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 570, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 333, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1554, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 258, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 239, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 196, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 246, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 73, in pytest_runtestloop
    self.run_one_test(torun)
  File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 87, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 96, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 182, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 234, in from_call
    result = func()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 207, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 131, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1435, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 166, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/workspace/source/testing/scripts/test_rolling_updates.py", line 379, in test_rolling_update10
    r = initial_rest_request("mymodel", namespace)
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 134, in initial_rest_request
    names=names,
  File "/workspace/source/testing/scripts/seldon_e2e_utils.py", line 107, in rest_request
    logging.warning("Bad status:", r.status_code)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1855, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1313, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1437, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1447, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1509, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 858, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/_pytest/logging.py", line 301, in emit
    logging.StreamHandler.emit(self, record)
Message: 'Bad status:'
Arguments: (404,)

[gw2] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update8 
test_rolling_updates.py::test_rolling_update_deployment[graph7.json-graph8.json] Error from server (NotFound): error when deleting "../resources/graph6svc.json": seldondeployments.machinelearning.seldon.io "mymodel" not found

[gw0] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update9 
[gw1] PASSED test_rolling_updates.py::TestRollingHttp::test_rolling_update10 Error from server (NotFound): error when deleting "../resources/graph8.json": seldondeployments.machinelearning.seldon.io "mymodel" not found
Error from server (NotFound): error when deleting "../resources/graph8.json": seldondeployments.machinelearning.seldon.io "mymodel" not found

[gw3] PASSED test_rolling_updates.py::test_rolling_update_deployment[graph1.json-graph8.json] 
[gw2] PASSED test_rolling_updates.py::test_rolling_update_deployment[graph7.json-graph8.json] 

=================================== FAILURES ===================================
_____________________ TestRollingHttp.test_rolling_update5 _____________________
[gw0] linux -- Python 3.6.0 /usr/local/bin/python

self = <test_rolling_updates.TestRollingHttp object at 0x7f8aa96e77f0>

    def test_rolling_update5(self):
        namespace = "test-rolling-update-5"
        retry_run(f"kubectl create namespace {namespace}")
        retry_run(f"kubectl apply -f ../resources/graph1.json -n {namespace}")
        wait_for_rollout("mymodel-mymodel-e2eb561", namespace)
        logging.warning("Initial request")
        r = initial_rest_request("mymodel", namespace)
        assert r.status_code == 200
        assert r.json()["data"]["tensor"]["values"] == [1.0, 2.0, 3.0, 4.0]
        retry_run(f"kubectl apply -f ../resources/graph6.json -n {namespace}")
        r = initial_rest_request("mymodel", namespace)
        assert r.status_code == 200
        assert r.json()["data"]["tensor"]["values"] == [1.0, 2.0, 3.0, 4.0]
        i = 0
        for i in range(50):
            r = rest_request_ambassador("mymodel", namespace, API_AMBASSADOR)
>           assert r.status_code == 200
E           assert 504 == 200
E             -504
E             +200

test_rolling_updates.py:196: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:61 Successfully ran command: kubectl create namespace test-rolling-update-5
WARNING  root:seldon_e2e_utils.py:61 Successfully ran command: kubectl apply -f ../resources/graph1.json -n test-rolling-update-5
WARNING  root:seldon_e2e_utils.py:50 Successfully waited for deployment mymodel-mymodel-e2eb561
WARNING  root:test_rolling_updates.py:185 Initial request
WARNING  root:seldon_e2e_utils.py:61 Successfully ran command: kubectl apply -f ../resources/graph6.json -n test-rolling-update-5
=================== 1 failed, 23 passed in 774.18s (0:12:54) ===================
make: *** [Makefile:68: test] Error 1
kind delete cluster
Deleting cluster "kind" ...
$KUBECONFIG is still set to use /builder/home/.kube/kind-config-kind even though that file has been deleted, remember to unset it
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
[31m
Pipeline failed on stage 'end-to-end' : container 'step-test-end-to-end'. The execution of the pipeline has stopped.[0m
