
Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-t4vcv[0m
{"level":"warn","ts":1575976514.6293564,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1575976514.629754,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-zfb6r[0m
{"level":"warn","ts":1575976516.3872411,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1575976516.3885005,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1231-in-trwk8[0m
{"level":"warn","ts":1575976521.8548565,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1575976525.5957398,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:1d662a0c418bb12dfc1ec3bc6b7584429d2ff485,1231:957a31f6d1a133807a198c1a0a2f2379b819abf7
DEBUG: ran git fetch --unshallow origin 957a31f6d1a133807a198c1a0a2f2379b819abf7: 1d662a0c418bb12dfc1ec3bc6b7584429d2ff485: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 1d662a0c418bb12dfc1ec3bc6b7584429d2ff485 in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge 957a31f6d1a133807a198c1a0a2f2379b819abf7 in 
Merged SHA f43ef91c096de6f127f3049d6fa46bdbd2d9b1f2 with commit message 'Merge commit '957a31f6d1a133807a198c1a0a2f2379b819abf7'' into base branch master
Merged SHA 957a31f6d1a133807a198c1a0a2f2379b819abf7 with commit message 'update references to core-builder to use 0.8' into base branch master
Merged SHA 57ad4abd506e80403877ce1880caf7d602ad7d53 with commit message 'update core-builder to use openjdk:13.0.1-jdk-buster base image' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1231
+ BUILD_NUMBER=3
+ PIPELINE_CONTEXT=integration
++ cat
+++ date
+ COMMENT_MSG='Tue Dec 10 11:15:34 UTC 2019
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1231/3.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1231 --build=3'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1231 '--comment=Tue Dec 10 11:15:34 UTC 2019
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1231/3.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1231 --build=3'

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1231-in-96dmr[0m
{"level":"warn","ts":1575976537.209126,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1575976537.2133265,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /pvc/pr-build-comment/workspace\""}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1231-in-tjww4[0m
{"level":"warn","ts":1575976537.8060791,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1575976538.0201206,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"cp -r /workspace/source/. /pvc/pr-build-comment/workspace\""}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mend-to-end[0m and container [32mstep-credential-initializer-nnbk6[0m
{"level":"warn","ts":1575976575.9663513,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1575976575.9667993,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mend-to-end[0m and container [32mstep-working-dir-initializer-h8nrj[0m
{"level":"warn","ts":1575976577.0012848,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1575976577.0027788,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mend-to-end[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mend-to-end[0m and container [32mstep-create-dir-workspace-hfkl6[0m
{"level":"warn","ts":1575976583.0843172,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1575976583.086399,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mend-to-end[0m and container [32mstep-source-copy-workspace-sl2vj[0m
{"level":"warn","ts":1575976583.323804,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1575976585.1381202,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"cp -r /pvc/pr-build-comment/workspace/. /workspace/source\""}

Showing logs for build [32mseldonio-seldon-core-pr-1231-in-3[0m stage [32mend-to-end[0m and container [32mstep-test-end-to-end[0m
Starting Docker: docker.
[SETUP] Waiting for Docker to be ready, sleeping for 1 seconds ...
[SETUP] Waiting for Docker to be ready, sleeping for 2 seconds ...
[SETUP] Waiting for Docker to be ready, sleeping for 3 seconds ...
[SETUP] Waiting for Docker to be ready, sleeping for 4 seconds ...
[SETUP] Waiting for Docker to be ready, sleeping for 5 seconds ...
[SETUP] Reached maximum attempts, not waiting any longer ...
kind create cluster --config kind_config.yaml
Error: could not list clusters: failed to list nodes: exit status 1
make: *** [Makefile:7: kind_create_cluster] Error 1
Existing kind cluster or failure starting - 2
kind delete cluster
Error: could not list clusters: failed to list nodes: exit status 1
make: *** [Makefile:10: kind_delete_cluster] Error 1
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
kind_test_all.sh: line 97: TEST_EXIT_VALUE: unbound variable
[31m
Pipeline failed on stage 'end-to-end' : container 'step-test-end-to-end'. The execution of the pipeline has stopped.[0m
